# Generated by Django 2.1.1 on 2019-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_num',
            field=models.IntegerField(default=1),
        ),
    ]
