# Generated by Django 2.1.1 on 2019-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_num',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_make',
            field=models.CharField(default='', max_length=30),
        ),
    ]
